version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/gluecodes-framework

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install --production=false
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm test
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/gluecodes-framework

  deploy:
    docker:
      - image: circleci/python:2.7-jessie

    working_directory: ~/gluecodes-framework

    steps:
      - run:
          name: install awscli
          command: sudo pip install awscli
      - run:
          name: update NodeJS
          command: |
            curl -sSL "https://nodejs.org/dist/v12.14.1/node-v12.14.1-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v12.14.1-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: delete libVersions.json if exists
          command: rm -f ~/gluecodes-framework/libVersions.json
      - run:
          name: download libVersions.json
          command: aws s3 sync s3://gluecodes-components/ ~/gluecodes-framework --exclude '*' --include 'libVersions.json'
      - run:
          name: pack components
          command: node ~/gluecodes-framework/scripts/packComponents.js
      - run:
          name: push new versions of components and libVersions.json backup
          command: aws s3 cp ~/gluecodes-framework/dist/packages/ s3://gluecodes-components/ --acl public-read --recursive --exclude '*' --include '*.tar.gz' --include '**/index.js' --include '**/styles.css'
      - run:
          name: push updated libVersions.json
          command: aws s3 cp ~/gluecodes-framework/libVersions.json s3://gluecodes-components/libVersions.json --acl public-read

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: major/solidjs
